global using Category5ScoutingV2;
global using Category5ScoutingV2._Database;
global using Category5ScoutingV2._Tba;
global using Category5ScoutingV2._Tba.Schemas;
global using DSharpPlus;
global using DSharpPlus.CommandsNext;
global using DSharpPlus.CommandsNext.Attributes;
global using DSharpPlus.Interactivity;
global using DSharpPlus.Interactivity.Extensions;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Newtonsoft.Json;
global using static Category5ScoutingV2.Utils;